<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>de.schosin.ecs</groupId>
        <artifactId>ecs-plugins-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    
    <groupId>de.schosin.ecs.plugins</groupId>
    <artifactId>ecs-plugins-archetype</artifactId>

    <dependencies>
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-core</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-codegen</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
    
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <annotationProcessorPath>
                            <groupId>de.schosin.ecs</groupId>
                            <artifactId>ecs-codegen</artifactId>
                            <version>${project.version}</version>
                        </annotationProcessorPath>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-AcompositionParams=${codegen.compositionParams}</arg>
                        <arg>-AarchetypeParams=${codegen.archetypeParams}</arg>
                        <arg>-AtransmuterParams=${codegen.transmuterParams}</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>