<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>de.schosin.ecs</groupId>
    <artifactId>parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    
    <modules>
        <module>codegen</module>
        <module>api</module>
        <module>utils</module>
        <module>core</module>
        <module>test</module>
        <module>plugins</module>
        <module>worlds</module>
        <module>benchmark</module>
	    <module>bom</module>
    </modules>
  
    <properties>
        <!-- handwritten tests require minimum of 8, or disabled test compilation -->
        <codegen.compositionParams>8</codegen.compositionParams>
        <codegen.archetypeParams>8</codegen.archetypeParams>
        <codegen.transmuterParams>8</codegen.transmuterParams>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        
        <jspecify.version>1.0.0</jspecify.version>
        <jackson.version>2.19.0</jackson.version>
        
        <hibernate.validator.version>8.0.2.Final</hibernate.validator.version>
        <glassfish.expressly.version>5.0.0</glassfish.expressly.version>
        
        <bytebuddy.version>1.17.5</bytebuddy.version>
        
        <junit.version>5.12.2</junit.version>
        <junit-pironeer.version>2.3.0</junit-pironeer.version>
        <assertj.version>3.27.2</assertj.version>
        <archunit.version>1.4.0</archunit.version>
        <jmh.version>1.37</jmh.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>de.schosin.ecs</groupId>
                <artifactId>codegen</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.jspecify</groupId>
                <artifactId>jspecify</artifactId>
                <version>${jspecify.version}</version>
            </dependency>
                        
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
                
            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${hibernate.validator.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.expressly</groupId>
                <artifactId>expressly</artifactId>
                <version>${glassfish.expressly.version}</version>
            </dependency>
                
            <dependency>
              <groupId>net.bytebuddy</groupId>
              <artifactId>byte-buddy</artifactId>
              <version>${bytebuddy.version}</version>
            </dependency>
            
            <dependency>
                <groupId>org.openjdk.jmh</groupId>
                <artifactId>jmh-core</artifactId>
                <version>${jmh.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openjdk.jmh</groupId>
                <artifactId>jmh-generator-annprocess</artifactId>
                <version>${jmh.version}</version>
            </dependency>
        
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.junit-pioneer</groupId>
                <artifactId>junit-pioneer</artifactId>
                <version>${junit-pironeer.version}</version>
            </dependency>
            <dependency>
                <groupId>com.tngtech.archunit</groupId>
                <artifactId>archunit-junit5</artifactId>
                <version>${archunit.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
