<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>de.schosin.ecs</groupId>
        <artifactId>ecs-storage-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    
    <groupId>de.schosin.ecs.storage</groupId>
    <artifactId>ecs-storage-archetype-storage-test</artifactId>

    <dependencies>
        <dependency>
            <groupId>de.schosin.ecs.storage</groupId>
            <artifactId>ecs-storage-archetype-storage</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.storage</groupId>
            <artifactId>ecs-storage-test-suite</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>de.schosin.ecs.storage</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.plugins</groupId>
            <artifactId>ecs-plugins-wildcards</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>