<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>de.schosin.ecs</groupId>
        <artifactId>ecs-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    
    <artifactId>ecs-worlds</artifactId>

    <dependencies>
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-core</artifactId>
            <version>${project.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>${storage.impl.groupId}</groupId>
            <artifactId>${storage.impl.artifactId}</artifactId>
            <version>${storage.impl.version}</version>
            <scope>runtime</scope>
        </dependency>
        
        <dependency>
            <groupId>de.schosin.ecs.plugins</groupId>
            <artifactId>ecs-plugins-state</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.plugins</groupId>
            <artifactId>ecs-plugins-archetype</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.plugins</groupId>
            <artifactId>ecs-plugins-transmuter</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.plugins</groupId>
            <artifactId>ecs-plugins-composition</artifactId>
            <version>${project.version}</version>
        </dependency>
    
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
