package de.schosin.ecs.examples.simple.example4_componentSets;

import de.schosin.ecs.api.components.ComponentSet;
import de.schosin.ecs.api.components.ComponentSetConfig;
import de.schosin.ecs.api.components.Relation.EntityRelation;
import de.schosin.ecs.api.components.Result.ComponentRelationResult;
import de.schosin.ecs.api.components.mappers.ComponentSetMapper;
import de.schosin.ecs.api.components.types.ComponentSetType;
import de.schosin.ecs.api.components.types.ComponentType;
import de.schosin.ecs.examples.simple.AbstractExample;
import de.schosin.ecs.examples.simple.compositions.Position;
import de.schosin.ecs.examples.simple.compositions.Velocity;
import de.schosin.ecs.examples.simple.example4_componentSets.FirstComponentSet.Processor;
import de.schosin.ecs.plugins.composition.Composition;
import de.schosin.ecs.plugins.composition.CompositionSet;

@SuppressWarnings("unused")
public class ComponentSetExample extends AbstractExample {

    /**
     * Another type of component is {@link ComponentSetType}. This type describes a concrete
     * {@link ComponentSet}, which is not a regular component that can be assigned to an entity,
     * but describes a set of components in a type-safe manner.
     * 
     * <p>
     * To achieve that, component sets are generated by the annotation processor "ecs-build-tools-codegen-apt".
     * See the {@code <build />} section of the {@code pom.xml}. To generate a component set, a method
     * has to be annotated with {@link ComponentSetConfig} that accepts an int for the entityId as the 
     * first parameter and valid component arguments for the remaining parameters.
     * 
     * <p>
     * A valid component argument in this case is any type that can occur in the {@code R} of the built-in
     * {@link ComponentType ComponentType<T, R>}. A regular POJO component, a {@link ComponentRelationResult},
     * or a {@link EntityRelation} are just examples of valid parameter types.
     */
    public static void main(String[] args) {
        useFirstComponentSet();
        removeEntities();
        System.out.println();
    }

    /**
     * This method describes a component set with the two components.
     * 
     * @param entityId mandatory first argument must be the entityId
     * @param position position component
     * @param velocity velocity component
     */
    @ComponentSetConfig("FirstComponentSet")
    private static void processSimpleComponents(int entityId, Position position, Velocity velocity) {
        // skip this for now, it will be used at a later time
        System.out.println("Method reference - Entity %d: %s / %s".formatted(entityId, position, velocity));
    }

    private static void useFirstComponentSet() {
        // Let's create a couple of entities
        var entity1 = world.createEntity();
        var entity2 = world.createEntity(new Position(2, 2));
        var entity3 = world.createEntity(new Velocity(30, 30));
        var entity4 = world.createEntity(new Position(4, 4), new Velocity(40, 40));

        // The generated type contains a ComponentType field TYPE that descibes the generated component set. 
        ComponentSetType<FirstComponentSet, Processor> componentSetType = FirstComponentSet.TYPE;

        // When used as a component type, the set is assigned to both T (write) and R (read)
        ComponentType<FirstComponentSet, FirstComponentSet> componentType = componentSetType;

        // The mapper for a component set is of type ComponentSetMapper
        ComponentSetMapper<FirstComponentSet> mapper = world.getComponents(FirstComponentSet.TYPE);

        /*
         * When getting a component set for an entity, it will be non-null as long as the entity
         * has atleast one of the components of the set.
         */
        System.out.println("Get - Entity %d: %s".formatted(entity1, mapper.get(entity1)));
        System.out.println("Get - Entity %d: %s".formatted(entity2, mapper.get(entity2)));
        System.out.println("Get - Entity %d: %s".formatted(entity3, mapper.get(entity3)));
        System.out.println("Get - Entity %d: %s".formatted(entity4, mapper.get(entity4)));

        /*
         * When creating a composition and passing along only a single component set type after the 
         * builder, a CompositionSet will be returned.
         * 
         * Note that its type argument is not the set, but an inner type called Processor. 
         * This functional interface defines how the callbacks for process, inserted and removed work.
         */
        CompositionSet<FirstComponentSet.Processor> composition = world.createComposition(Composition.all(), FirstComponentSet.TYPE);

        /*
         * The signature will match the annotated method (processSimpleComponents).
         * 
         * Note that the builder matches all entities, so it will also process entity1, which does not
         * have any of the components.
         */
        composition.process((entityId, position, velocity) -> {
            System.out.println("Lambda - Entity %d: %s / %s".formatted(entityId, position, velocity));
        });

        /*
         * Because the signature matches the method the component set was derived from, that method itself
         * can be used with a method reference.
         */
        composition.process(ComponentSetExample::processSimpleComponents);

        /*
         * A component set type can not be used in Composition.Builder. It simply does not carry the necessary information
         * as this time. The component set has all necessary information, but not in a form that is available in API
         * without unsafe reflection.
         * 
         * Just don't use component set types for Composition.Builder. At best it would be a glorified Composition.one(...) anyway
         * to match the behaviour of ComponentSetMapper#get(int).
         */
        CompositionSet<FirstComponentSet.Processor> componentSetComposition = world.createComposition(Composition.all(componentSetType), FirstComponentSet.TYPE);
    
        componentSetComposition.process((entityId, position, velocity) -> {
            System.out.println("this will not be printed. unless this was actually implemented and this example was forgotten. please raise an issue if that is the case.");
        });
    }

}
