<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>de.schosin.ecs</groupId>
        <artifactId>ecs-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    
    <artifactId>ecs-integration-tests</artifactId>
    
    <properties>
        <maven.install.skip>true</maven.install.skip>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-worlds</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.plugins</groupId>
            <artifactId>ecs-plugins-wildcards</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.plugins.experimental</groupId>
            <artifactId>ecs-plugins-experimental-system</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.schosin.ecs.buildtools</groupId>
            <artifactId>ecs-build-tools-codegen-apt</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
    
        <dependency>
            <groupId>de.schosin.ecs</groupId>
            <artifactId>ecs-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <skipIfEmpty>true</skipIfEmpty>
                </configuration>
            </plugin>
        </plugins>    
    </build>
</project>
